export const error = (fn: any) => (...args: any) => fn(...args).catch(args[2]);